### ISSUE TITLE
botocore.exceptions.NoCredentialsError: Unable to locate credentials problem

### ISSUE THREAD

**Issue by onurdegerli** [HDE/python-lambda-local#19]
I installed the npm package and tried to run a command below:

python-lambda-local -l lib/ -f lambda_handler test.py event.json

But I get the error below:

The first:

`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

The second:
```
During handling of the above exception, another exception occurred:
TypeError: Object of type 'FrameSummary' is not JSON serializable
```

The second one might be related to first one but I am not sure.

I also stored my aws credentials under the /root/.aws folder.

**Comment by yxd-hde** [comment]
This is not an issue of `python-lambda-local`. Please check your code and usage of boto library.

**Comment by onurdegerli** [comment]
How can I add credentials with using boto?
I added my credentials info into the ~/.aws/config and ~/.aws/credentials files.

**Comment by onurdegerli** [comment]
I set the credentials and succeed to run the code.
But when it tries to run `s3_client.upload_file` it gives an error like below. Actually, it gives empty error and I don't have any idea.

[root - ERROR - 2017-08-01 13:56:16,652] RESULT:
Timeout after 3 seconds.
