### ISSUE TITLE
What exactly is the purpose of `--arn-string`

### ISSUE THREAD

**Issue by felipe1982** [HDE/python-lambda-local#23]
Originally, I had thought this was the ARN of a Role to use for my Lambda function. After a while, I realised that can't be right.

I tried some "dummy" value of a ARN of a lambda function, and it did not fail. Is there any validation of `--arn-string`?

What exactly is the function/purpose of `--arn-string`?

**Comment by yxd-hde** [comment]
It is there to be compatible with the context object in the real AWS lambda environment.

http://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html

It is the `invoked_function_arn`.
