### ISSUE TITLE
Make python-lambda-local work with Python 3.7

### ISSUE THREAD

**Issue by andypaterson40** [HDE/python-lambda-local#31]
Is there any scope to get PLL to work with Python 3.7?

**Comment by yxd-hde** [comment]
Currently, AWS Lambda runtime environment doesn't support Python 3.7 yet.
And in HDE we haven't tested whether this tool works with Python 3.7 or not.
Any test and result is welcomed.

**Comment by yxd-hde** [comment]
https://aws.amazon.com/blogs/compute/python-3-7-runtime-now-available-in-aws-lambda/

**Comment by emepetres** [comment]
I've tested and AFAIK it is working without issues.

**Comment by ume-daniel** [comment]
in main.py, use the default urllib3 by replacing
from botocore.vendored.requests.packages import urllib3
with
import urllib3

**Comment by yxd-hde** [comment]
@ume-daniel Thanks! With #55 , I think this is already fixed.
