### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by maitri2705** [HDE/python-lambda-local#34]
hi, 
Here, these are all the steps which I am following to deploy python lambda function.
first of all, I am making .py file of the function.
then, I am giving these commands from the command prompt:
virtualenv xyz (this will create a folder named as xyz)
source xyz/bin/activate
pip install python-lambda
pip install pymysql
lambda init 
then lambda deploy command

In this process, after deployment, I am getting this error:
Unable to import module: No module named pymysql

Is this because of changes in python-lambda?

**Comment by maitri2705** [comment]
I found the issue,
if i install pymysql from pip 18.0, it is not working, but if I install from pip 10.0.1, it's working.

**Comment by yxd-hde** [comment]
Sorry but this is the repository of `python-lambda-local` instead of `python-lambda`.
