### ISSUE TITLE
UnicodeDecodeError gbk codec can't decode byte

### ISSUE THREAD

**Issue by jjuu** [HDE/python-lambda-local#36]
**OS: windows 10
virtualenv: 16.0.0
python version: 3.6.7 **

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting python-lambda-local
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/48/2e/728cd8091a7f4214e8098b9dbaeec5c79eef36ef2e85c5216cd414df09c4/python-lambda-local-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\brucecatcat\AppData\Local\Temp\1\pip-install-n7mvbtfb\python-lambda-local\setup.py", line 30, in <module>
        long_description=open("README.rst").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2047: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\brucecatcat\AppData\Local\Temp\1\pip-install-n7mvbtfb\python-lambda-local\

**Comment by yxd-hde** [comment]
A PR is created and it is supposed to fix this.

However, if you don't want to wait for a new release, it might be possible to install if your system encoding is set to UTF8 instead of GBK.
