### ISSUE TITLE
doesnt work on windows

### ISSUE THREAD

**Issue by otakusid** [HDE/python-lambda-local#4]
Hi, looks like your package doesn't work on windows. Here is output that I have:

> $ python-lambda-local -f lambda_handler application.py event.json
> Loading function
> [root - INFO - 2016-05-19 14:02:20,864] Event: {u'key': u'value'}
> [root - INFO - 2016-05-19 14:02:20,865] START RequestId: d4e78245-c1b6-4c4d-9618-f7d61cae2493
> [root - INFO - 2016-05-19 14:02:20,865] END RequestId: d4e78245-c1b6-4c4d-9618-f7d61cae2493
> [root - INFO - 2016-05-19 14:02:20,867] RESULT:
> {
>     "stackTrace": [
>         [
>             "d:\\_work\\infrastructure\\aws\\lambda\\big_brother\\src\\venv\\lib\\site-packages\\lambda_local\\main.py",
>             79,
>             "execute",
>             "with time_limit(context.timeout):"
>         ],
>         [
>             "C:\\tools\\python2\\Lib\\contextlib.py",
>             17,
>             "__enter__",
>             "return self.gen.next()"
>         ],
>         [
>             "d:\\_work\\infrastructure\\aws\\lambda\\big_brother\\src\\venv\\lib\\site-packages\\lambda_local\\timeout.py",
>             18,
>             "time_limit",
>             "signal.signal(signal.SIGALRM, signal_handler)"
>         ]
>     ],
>     "errorType": "AttributeError",
>     "errorMessage": "'module' object has no attribute 'SIGALRM'"
> }
> [root - INFO - 2016-05-19 14:02:20,869] REPORT RequestId: d4e78245-c1b6-4c4d-9618-f7d61cae2493  Duration: 0.82 ms

**Comment by yxd-hde** [comment]
No, it doesn't. It uses UNIX signal to implement timeout feature.

**Comment by otakusid** [comment]
(T_T)

**Comment by FlavioCestari** [comment]
Windows support is in pipeline/backlog?

**Comment by adammarton** [comment]
> No, it doesn't. It uses UNIX signal to implement timeout feature.

@yxd-hde you may want to emphasize this in the documentation.

**Comment by 1jkunz1** [comment]
Any update on this ?
