### ISSUE TITLE
Exceptions thrown in handler function make process hang

### ISSUE THREAD

**Issue by danielthepope** [HDE/python-lambda-local#57]
If the handler function throws an error, the execution of `lambda_call` never returns. A stack trace is printed containing the message `TypeError: Object of type FrameSummary is not JSON serializable`.

Looks like this is caused in line 127 of main.py (where you're setting `stackTrace`):
```python
        result = json.dumps({
            "errorMessage": str(err[1]),
            "stackTrace": traceback.extract_tb(err[2]),
            "errorType": err[0].__name__
        }, indent=4, separators=(',', ': '))
```
`json.dumps` is not happy with serializing an array of FrameSummary objects, which is what `extract_tb` returns.

**Comment by kevinpowe** [comment]
Thank you so much for this. Works perfectly now!
