### ISSUE TITLE
main.run() should return results

### ISSUE THREAD

**Issue by slass100** [HDE/python-lambda-local#67]
More of a feature request perhaps, but if you add 'return result' to main.run(), then we can integrate with pytest.  

```
*** main.py	2020-03-13 16:14:47.990222857 +0000
--- main.py.orig	2020-03-13 16:14:29.062115892 +0000
***************
*** 86,93 ****
      if err_type is not None:
          sys.exit(EXITCODE_ERR)
  
-     return result
- 
  
  def _runner(loader, event, context):
      logger = logging.getLogger()
--- 86,91 ----
```

Eg.

```
import os
import unittest
from lambda_local.main import run

#python-lambda-local -f lambda_handler src/lambda_function.py plltest/event1.json  -e plltest/env1.json
class PLL:
    event = 'plltest/event1.json'
    function = 'lambda_handler'
    file = 'src/lambda_function.py'
    environment_variables = 'plltest/env1.json'
    timeout = 3
    library = None
    version_name = ''
    arn_string = ''

class TestHandlerCase(unittest.TestCase):

    def test_response(self):
        res = run(PLL())
        data = {'Message': 'Hello World', 'Action': 'None'}
        self.assertEqual(res, data)

if __name__ == '__main__':
    unittest.main()

```

**Comment by yxd-hde** [comment]
The API the library is exposing is

```
def call(func, event, context, environment_variables={}):
...
```

Is there any reason why you are not using this for testing?

**Comment by slass100** [comment]
The honest answer is because I started at main(), which led me to run().

Now that I've used call(), I think I still prefer run() because:
- run() does not need to also import Context() or read_event() into my code
- it is easier (for me) to map between the command-line args and the run() args namespace

I really appreciate your response.  I'll probably write a helper function that uses a dict() of the command-line flags and invokes call() so that I can easily run pytest or python-lamdba-local without having to think too hard.

Thanks again for your response.  You can close this issue.

**Comment by yxd-hde** [comment]
Thanks for the explanation. Close it.
